server:
  port: 12334

spring:
  datasource:
    url: jdbc:sqlserver://192.168.0.123:1433;databasename=Water_rain
    username: sa
    password: abcABC123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#log
logging:
  level:
    com.zz: debug
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zz.pojo
